### ISSUE TITLE
Cannot run 'Dialog' example on Mac OS 9.2.2

### ISSUE THREAD

**Issue by nehalem501** [autc04/Retro68#110]
I've built Retro68 on a Linux system with all default options and the MPW 3.5 interfaces. Everything built successfully.

I tried running the carbon Dialog example on Mac OS 9.2.2 (emulated in QEMU).

`The application "Dialog" could not be opened because ">>CarbonLib<<" could not start up.`

I've checked that CarbonLib is present in the System Extensions. With Mac OS 9.2.2 the default supplied version is 1.4, because of the error I tried to run 'Dialog' again after installing the CarbonLib 1.6 update, but I still have the same error.

The Dialog example was transferred to the emulated machine by using the Dialog.dsk disk image.

See supplied screenshot.

<img width="449" alt="Screenshot 2020-07-22 at 12 56 37" src="https://user-images.githubusercontent.com/4194367/88168688-106d4000-cc1b-11ea-9b8d-12a9b2d9c4a3.png">

**Comment by autc04** [comment]
Turns out that Carbon APPS need to have the `isHighLevelEventAware` flag set in their `SIZE` resource when running on MacOS 9, but not when running on Mac OS X.

I actually fixed that for the default `SIZE` resource a while ago, but the Dialog sample comes with its own `SIZE` resource in `dialog.r`.
 
Thanks for the report!
