### ISSUE TITLE
Should I use 2019.8.2 or master?

### ISSUE THREAD

**Issue by ryandesign** [autc04/Retro68#126]
I just found Retro68 today and just reading about it already makes me so happy. Thank you, thank you, thank you!

I'd like to add Retro68 to MacPorts. Which version should we offer: the latest release 2019.8.2 or the latest commit on master? I noticed that 2019.8.2 predates multiversal and requiring the user to supply the Apple Universal Interfaces would complicate installation, so I'm inclined to use the latest commit from both Retro68 and multiversal unless you recommend otherwise.

If I use master, is it ok for me to assign a date-based version number, e.g. 2021.4.13 for the latest commit as of now?

**Comment by autc04** [comment]
Cool :-)

I'd say go with the current version, and let's just give it another release tag. IIRC, 2019.8 was tagged because someone tried to make a homebrew release (it ultimately went nowhere back then because of the universal interfaces issue), and 2019.8.2 was a second release the same month for bugfix purposes.

I don't have a proper release process yet. I'm basically jsut working on it when I feel like it, so bleeding edge is best unless something went wrong. I'm happy to tag any release that is reported to work, especially if it's referenced by some port script.

**Comment by ryandesign** [comment]
Great, I'll use the latest. There are still some things I'm working out which I'll probably file more issues or pull requests for, so no rush to tag anything just yet.
