### ISSUE TITLE
conflicting declaration errors

### ISSUE THREAD

**Issue by bparker06** [autc04/Retro68#46]
I'm getting this trying to build from the latest HEAD on Linux (Ubuntu 16.04):

http://dpaste.com/1QQ4JGT

Any idea what is wrong?

**Comment by autc04** [comment]
Looks like a copy of Apple's math.h ended up in `/storage/libretro/Retro68-build/toolchain/CIncludes/math.h`. The `prepare-headers.sh` script is supposed to skip that file, because, as you see, it causes trouble (the newlib  C library supplies its own `math.h`).
My first theory would be that the `CIncludes/math.h` file is left over from an old build of Retro68 - remove that directory (or all of Retro68-build/toolchain to be safe) and try again.
