### ISSUE TITLE
Bad destination address

### ISSUE THREAD

**Issue by antscode** [autc04/Retro68#50]
Hi there,

I'm trying to port a screensaver originally written in Think C to Retro68. I've converted the INIT so far, however it's crashing on startup.

I've traced the issue to the patches applied to certain system functions such as SystemTask. When the patched function attempts to call the original system function, it crashes with "Bad destination address".

It must be something to do with the memory allocation of the patches, but I don't really know where to go from here.

Attached is the source and the StdLog from MacsBug. Any help would be much appreciated.

Thanks.

[StdLog.txt](https://github.com/autc04/Retro68/files/1774218/StdLog.txt)
[BasicBlack.zip](https://github.com/autc04/Retro68/files/1774202/BasicBlack.zip)

**Comment by autc04** [comment]
Ok, I see what's going on here.

Traditional Mac code resources (INITs) use "PC Relative" addressing in their code. This means that all jumps and function calls are stored as relative offsets in the code. Unfortunately, on the 68K, that means 16-bit offsets, hence a 32K limit on code size.

GCC uses 32-bit absolute addresses by default. Once your program/INIT/etc. gets loaded, those addresses are *wrong*, and RETRO68_RELOCATE() figures out just how wrong they are and patches the code in memory to correct it.

Now, the main routine of Basic Black copies a part of the INIT's code (the part between `StartPatchCode` and `EndPatchCode`) to a new block in the system heap, so all the carefully patched absolute addresses are wrong *again*. Hence the crash.

If I was writing this `INIT`, I would not do the copying at all, but rather just set the resource attributes to System Heap and Locked, and Not Purgeable. Of course, this means that all the code in `main()` stays in memory, so it wastes some memory, but it is much simpler. You get to use global variables and everything. 
Just use the function addresses in SetTrapAddress directly, without the offset calculations, and replace `PatchGlobals` and associated pointer arithmetic by simple global variables.
Warning: I might be overlooking some other important reason why the original author copied the code to a new block, so as always, there might be unexpected problems.

*Theoretically* (this means I haven't tested it recently and it might just break everything) `gcc` supports 16-bit relative addressing via the `-mpcrel` option, as long as your program is below 32KB. You might want to try that first, it *might* make the code magically work. But you still can't use global variables or any of the modern luxuries in the standard library in this case, because only a minimal part of your code will have been copied into the system heap.

**Comment by antscode** [comment]
Thanks so much for looking into this and the clear explanation. I'll give both of your suggestions a go and report back with my findings. Thanks again.

**Comment by antscode** [comment]
I've tried both techniques. Using `-mpcrel` unfortunately wasn't the magic solution - it crashed on startup. I didn't spent much time on this though, since I'm certain my resulting code will be greater than 32kb anyway.

I spent a lot more time on your first suggestion - but no matter what I try, my patched toolbox function always crashes with a "No procedure error". It seems as if the address of the function is still not right.

I've attached the _simplest_ of examples which just tries to patch a single toolbox function. If I could get this working then I think I can sort out the rest.

Hoping you can help?

[PatchTest.zip](https://github.com/autc04/Retro68/files/1783520/PatchTest.zip)

**Comment by autc04** [comment]
This time, I don't see anything at first glance. I'll try compiling & running it myself later.

**Comment by antscode** [comment]
I've made some progress. I came across this [MacTech Article](http://www.mactech.com/articles/mactech/Vol.05/05.10/INITinC/index.html) on writing INITs and it says that you need to call DetachResource on your INIT resource at system startup - otherwise the OS will purge it after it's run.

My test app is no longer crashing into MacsBug with "no procedure name" - but it's still locking up the OS. I think it could simply be that I've written my patched function incorrectly.

I'll keep on chipping away at it, but attached is the updated test app if you happen to spot anything.

[PatchTest2.zip](https://github.com/autc04/Retro68/files/1827590/PatchTest2.zip)

**Comment by antscode** [comment]
Success. The remaining problem was that I wasn't defining the global variable to the existing trap function as _pascal_:

    typedef pascal short(*SEProcPtr) (EventRecord *);
    SEProcPtr _oldSystemEvent;
    ...

**Comment by autc04** [comment]
Good work!
