### ISSUE TITLE
A4 Worlds in an INIT

### ISSUE THREAD

**Issue by antscode** [autc04/Retro68#52]
Hopefully a quick question: Do I need to worry about _A4 Worlds_ if I'm using your technique of using Global Variables in an INIT?

I've managed to migrate a few INITS to Retro68, and everything appears to be working - but I've blatantly commented out any lines of code that attempt to set an A4 world. It would appear that there are no Macintosh Toolbox functions for dealing with this - only proprietary libraries like Symantec or Metrowerks.

I actually have no idea what an A4 world even is - online documentation seems to be sparse.

**Comment by autc04** [comment]
Short version
------------------

You don't need to worry about A4 worlds.

If (and only if) you intend to use QuickDraw from your INIT or other non-application code, you *might* need to worry about A5 worlds.

Long version
-----------------

A4 and A5 are both address registers in the 68K processor.
A global variable will reside *somewhere* in memory. The trouble is, your program cannot know in advance *where* it is in memory.

The 68K processor has several "addressing modes", i.e. ways in which a machine language instruction can refer to memory. 

1. 32-bit absolute address
2. program counter relative, with 16-bit displacement
3. address register relative, with 16-bit displacement
4. others, which aren't relevant here.

The first one means that the  address (of a global variable, for example), is just there as part of the instruction:

    MOVE.L $00123456, D0  # read a Long word from address 0x123456 into the data register D0
     # for C programmers:  D0 = *(long*) 0x123456;

This is what gcc/Retro68 uses. But as we can't know in advance where the global variables will be, there has to be an additional step before the program runs where all these addresses in the code are corrected (*relocation*) - for INITs, you're calling that by hand, for applications, it's automatic.

Next, addresses can be specified relative to the current instruction, which is very useful, but unfortunately, the instructions only have room for a 16-bit relative distance, i.e. plus or minus 32 kilobytes. Programs often had more than 32K of code even back then, so this is not a general solution.

And third, if we manage to get the address of a memory block containing our global variables into an address register, such as `A5`, we can use that to find our global variables:

    MOVE.L -42(A5), D0   # read a Long word from the address that is 42 bytes below A5 into D0
      # for C programmers: D0 = *(long*) (A5 - 42);

Again, we're limited to 32KB (in either direction); this limitation became slightly annoying around 1990 or so, but it was still a lot better than what was going on under MS-DOS.

**Comment by autc04** [comment]
(continued from above)

When a classic Mac application is started, MacOS makes A5 point to the end of the memory block reserved for global variables. Compilers (GCC included) make sure to never use A5 for anything else, so its value is preserved all the time.
The memory areas surrounding A5 is called the "A5 world."

Code running in a code resource like an INIT can't (easily) set up its own A5 world, because everyone else expects A5 to remain unchanged all the time. So many classic Mac compilers just sacrificed another register, A4, to serve the same purpose for global variables in code resources, but that had to be set up manually with help from the developer.

Retro68 never uses A4 for that purpose, so you don't need to worry about A4, and it pretty much ignores A5, so you don't need to worry about that, either.

Unless...

QuickDraw
========

QuickDraw uses A5 to find its global variables. As in, the current value of A5, and as that never changes while one application is running (MultiFinder/System 7 handle things just right when switching between applications), you never need to worry about this in applications.

If you call a QuickDraw routine from a code resource, it really depends on where your code is called from. If you are called from regular application code (say, it's a desk accessory, a WDEF, or something like that), then you get the current application's A5, and you're fine.

If not, you might be in trouble and have to fiddle with `SetA5` and `SetCurrentA5` to get things working. (More details on request)

**Comment by antscode** [comment]
Thank you very much for the detailed explanation. So from what I understand, the `RETRO68_RELOCATE()` function really is the magic that allows INIT's and other code resources work using absolute memory addresses, and does away with A4 worlds and relative addresses. It's genius really.

This particular project won't need QuickDraw (the [project is here](https://68kmla.org/forums/index.php?/topic/54476-wifi-extension-development-thread/) if you're interested), but my other project based on the BasicBlack screensaver certainly will. The `SetA5` function is already used in the BasicBlack code when QuickDraw calls are required. It compiles and runs fine - so I just won't touch it!

Thanks again.

**Comment by autc04** [comment]
* Unfortunately not my idea :-), lots of other systems do it that way. For example, regular 32-bit Windows `DLL`s work that way, too, only the relocation code ships with the OS rather than with the compiler.

* Cool project! Too bad my only Ethernet-capable retro mac is already connected to my wired network at home...

* My above explanation is now a wiki page: https://github.com/autc04/Retro68/wiki/Global-Variables-and-Relocation-(68K)
